export const timeslots = [
    {
        id: 1,
        slottime: "10:00 AM - 10:15 AM",
        slotstart: "10:00",
        slotend: "10:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 2,
        slottime: "10:30 AM - 10:45 AM",
        slotstart: "10:30",
        slotend: "10:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 3,
        slottime: "11:00 AM - 11:15 AM",
        slotstart: "11:00",
        slotend: "11:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 4,
        slottime: "11:30 AM - 11:45 AM",
        slotstart: "11:30",
        slotend: "11:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 5,
        slottime: "12:00 PM - 12:15 PM",
        slotstart: "12:00",
        slotend: "12:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 6,
        slottime: "12:30 PM - 12:45 PM",
        slotstart: "12:30",
        slotend: "12:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 7,
        slottime: "1:00 PM - 1:15 PM",
        slotstart: "13:00",
        slotend: "13:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 8,
        slottime: "1:30 PM - 1:45 PM",
        slotstart: "13:30",
        slotend: "13:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 9,
        slottime: "2:00 PM - 2:15 PM",
        slotstart: "14:00",
        slotend: "14:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 10,
        slottime: "2:30 PM - 2:45 PM",
        slotstart: "14:30",
        slotend: "14:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 11,
        slottime: "3:00 PM - 3:15 PM",
        slotstart: "15:00",
        slotend: "15:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 12,
        slottime: "3:30 PM - 3:45 PM",
        slotstart: "15:30",
        slotend: "15:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 13,
        slottime: "4:00 PM - 4:15 PM",
        slotstart: "16:00",
        slotend: "16:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 14,
        slottime: "4:30 PM - 4:45 PM",
        slotstart: "16:30",
        slotend: "16:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 15,
        slottime: "5:00 PM - 5:15 PM",
        slotstart: "17:00",
        slotend: "17:15",
        isselected: false,
        isavailable: true,
    },
    {
        id: 16,
        slottime: "5:30 PM - 5:45 PM",
        slotstart: "17:30",
        slotend: "17:45",
        isselected: false,
        isavailable: true,
    },
    {
        id: 17,
        slottime: "6:00 PM - 6:15 PM",
        slotstart: "18:00",
        slotend: "18:15",
        isselected: false,
        isavailable: true,
    },
];